### ISSUE TITLE
Possible katex helper function

### ISSUE THREAD

**Issue by judemanutd** [MatejBransky/react-katex#1]
I am currently using the [talyssonoc/react-katex](https://github.com/talyssonoc/react-katex) and wanted to know if this library had helper functions such as 

- `katex.__parse(value);` 
- `katex.renderToString(value, {
            displayMode: false,
          })`

I could not find any documentation for the same and wanted to know if it is possible,

**Comment by MatejBransky** [comment]
Hi,
you can set all KaTeX options directly. [It's in the documentation](https://github.com/MatejBransky/react-katex#configuring-katex).

Why do you need `katex.__parse`?

**Comment by judemanutd** [comment]
@MatejBransky so I had a requirement where I am using draftjs and the user is allowed to type in rich text along with tex and I was rendering this on the fly by parsing through the text using regex and using `renderToString()` on the tex parts in order to get html which would then automatically be rendered by the browser.

**Comment by MatejBransky** [comment]
Then I think that you don't need this library for this purpose. You can use the KaTeX API directly.
