### ISSUE TITLE
Replace microbundle with tsdx

### ISSUE THREAD

**Issue by MatejBransky** [MatejBransky/react-katex#4]
**Description**

It seems that I need a lot of boilerplate around microbundle it doesn't contain settings for testing and TS. And it's frustrating that there are now a lot of warnings and errors when I install deps. Tsdx looks promising and it has support for testing right out of the box so I'll try to replace microbundle with tsdx.

**Expected**

Clean development environment.

**Comment by shilangyu** [comment]
Is this related to #3?  Could you elaborate on the problem? Im willing to help

**Comment by MatejBransky** [comment]
Hi, there aren't any problems anymore. Thanks for offer of help.
