### ISSUE TITLE
Hi, it failed to display piecewise function

### ISSUE THREAD

**Issue by RVillanuevaRVC** [MatejBransky/react-katex#42]
**Describe the bug**
When I use this lib to display piecewise function in "f(x) = \left\{\begin{array}{ll}-x & \quad x \leq 0 \\x & \quad x > 0\end{array}\right.",it alerted as "KaTeX parse error: Expected '}', got '&' at position 32: …n{array}{ll}-x &̲ quad x leq 0 x…"
. But this statement for PieceWise function works in https://katex.org/ wetsite.

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by MatejBransky** [comment]
Is your function spelled right? It doesn't work in https://katex.org/ website.

![image](https://user-images.githubusercontent.com/20944757/102711455-28c0b400-42ba-11eb-9588-a6422159f0ac.png)

**Comment by RVillanuevaRVC** [comment]
Sorry, it is my fault. The spelling should be:
f(x) = \left\{\begin{array}{ll}-x & \quad x \leq 0 \\x & \quad x > 0\end{array}\right.
rather than 
f(x) = \left{\begin{array}{ll}-x  & \quad x \leq 0 \x & \quad x > 0\end{array}\right.
