### ISSUE TITLE
No display mode & doesn’t work in Chrome?

### ISSUE THREAD

**Issue by lensbart** [MatejBransky/react-katex#6]
Hello,

Thanks for making this package. I ran into a couple of issues when trying to render a simple formula:

```jsx
<TeX
  block
  math={String.raw`F(x) = \int^a_b \frac{1}{3}x^3`}
  settings={{
    displayMode: true,
    output: 'mathml'
  }}
/>
```

- This doesn’t render in display mode (I tried with and without `block` and `settings.displayMode`)
- The default output is `htmlAndMathml`, just like KaTeX, but this does not correspond with the live examples (maybe because another version is used under the hood?)
- The output doesn’t render in Chrome on macOS Catalina, but it does on Safari & Firefox

Any help would be greatly appreciated!

**Comment by shilangyu** [comment]
Did you try rendering it with the same option directly with katex? Maybe it's a katex issue

**Comment by MatejBransky** [comment]
@lensbart Hi, if you still have any problem, could you, please, send an example (e.g. in CodeSandbox)?

**Comment by MatejBransky** [comment]
Chrome doesn't support MathML.

If you need to render the required math expression than you can remove the `output` property because it renders with the option `htmlAndMathml` by default ([see docs for katex](https://katex.org/docs/options.html)).
